[profile.default]
src = "."
out = "out"
libs = ["lib"]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
monad_testnet = "${MONAD_RPC_URL}"

[etherscan]
monad_testnet = { key = "${MONAD_ETHERSCAN_KEY}", url = "${MONAD_EXPLORER_API}" }
